#!name=ShadowRocket RU Advanced

https://raw.githubusercontent.com/.../00_core.conf
https://raw.githubusercontent.com/.../10_geo_ru.conf
https://raw.githubusercontent.com/.../20_russian_services.conf
https://raw.githubusercontent.com/.../40_global_servises.conf
