#!name=ShadowRocket RU Full

https://raw.githubusercontent.com/.../00_core.conf
https://raw.githubusercontent.com/.../10_geo_ru.conf
https://raw.githubusercontent.com/.../20_russian_services.conf
https://raw.githubusercontent.com/.../25_vk_group.conf
https://raw.githubusercontent.com/.../26_yandex_group.conf
https://raw.githubusercontent.com/.../30_global_blocked.conf
https://raw.githubusercontent.com/.../40_global_servises.conf
https://raw.githubusercontent.com/.../50_streaming.conf
https://raw.githubusercontent.com/.../60_crypto_opsec.conf
https://raw.githubusercontent.com/.../90_rewriters.conf
