#!name=10 Geo RU Direct
#!desc=Russian domains and IP addresses via DIRECT

[Rule]
# Country domains
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,su,DIRECT
DOMAIN-SUFFIX,xn--p1ai,DIRECT

# Russian IP addresses
GEOIP,RU,DIRECT
